### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by sevmardi** [yueruchen/Pedestrian-Synthesis-GAN#11]
Running training as is get the following

Got this issue first   #https://github.com/yueruchen/Pedestrian-Synthesis-GAN/issues/6#issue-371530057
I changed the code from this 

`netG.cuda(device_id=gpu_ids[0])`

to just `netG.cuda(gpu_ids[0])`

Running it again got me this
```
Traceback (most recent call last):
  File "train.py", line 35, in <module>
    model.optimize_parameters(only_d)
  File "/home/sevak/github/Pedestrian-Synthesis-GAN/models/pix2pix_model.py", line 179, in optimize_parameters
    self.backward_D_person()
  File "/home/sevak/github/Pedestrian-Synthesis-GAN/models/pix2pix_model.py", line 131, in backward_D_person
    self.person_fake = self.netD_person.forward(self.person_crop_fake)
  File "/home/sevak/github/Pedestrian-Synthesis-GAN/models/networks.py", line 480, in forward
    spp = self.spatial_pyramid_pool(x,1,[int(x.size(2)),int(x.size(3))],self.output_num)
  File "/home/sevak/github/Pedestrian-Synthesis-GAN/models/networks.py", line 453, in spatial_pyramid_pool
    x = maxpool(previous_conv)
  File "/home/sevak/python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sevak/python3/lib/python3.5/site-packages/torch/nn/modules/pooling.py", line 142, in forward
    self.return_indices)
  File "/home/sevak/python3/lib/python3.5/site-packages/torch/nn/functional.py", line 396, in max_pool2d
    ret = torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)

```

Any ideas?

**Comment by sevmardi** [comment]
**Update**: 
Just after updating torch to 1.0.0, run the cli command and got the following: 

```

Traceback (most recent call last):
  File "train.py", line 35, in <module>
    model.optimize_parameters(only_d)
  File "/home/sevak/github/Pedestrian-Synthesis-GAN/models/pix2pix_model.py", line 179, in optimize_parameters
    self.backward_D_person()
  File "/home/sevak/github/Pedestrian-Synthesis-GAN/models/pix2pix_model.py", line 131, in backward_D_person
    self.person_fake = self.netD_person.forward(self.person_crop_fake)
  File "/home/sevak/github/Pedestrian-Synthesis-GAN/models/networks.py", line 480, in forward
    spp = self.spatial_pyramid_pool(x,1,[int(x.size(2)),int(x.size(3))],self.output_num)
  File "/home/sevak/github/Pedestrian-Synthesis-GAN/models/networks.py", line 453, in spatial_pyramid_pool
    x = maxpool(previous_conv)
  File "/home/sevak/python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sevak/python3/lib/python3.5/site-packages/torch/nn/modules/pooling.py", line 148, in forward
    self.return_indices)
  File "/home/sevak/python3/lib/python3.5/site-packages/torch/_jit_internal.py", line 132, in fn
    return if_false(*args, **kwargs)
  File "/home/sevak/python3/lib/python3.5/site-packages/torch/nn/functional.py", line 425, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)[0]
  File "/home/sevak/python3/lib/python3.5/site-packages/torch/nn/functional.py", line 417, in max_pool2d_with_indices
    return torch._C._nn.max_pool2d_with_indices(input, kernel_size, _stride, padding, dilation, ceil_mode)
TypeError: max_pool2d_with_indices(): argument 'padding' must be tuple of ints, but found element of type float at pos 1



```

**Comment by yueruchen** [comment]
change `device_id` to `device`

**Comment by sevmardi** [comment]
@yueruchen  Tried this already. Same error as above. 

```
TypeError: max_pool2d_with_indices(): argument 'padding' must be tuple of ints, but found element of type float at pos 1

```

I am not sure whether this is a pytorch problem or the implementation itself. Would you mind trying it out on torch version 1.0 and see whether you get the same error.

**Comment by sevmardi** [comment]
Any updates on this one? Or is it just me  ?

**Comment by yifanjiang19** [comment]
Currently, I do not have any computational resource to try it.

But I believe the code can be directly run on 0.3 since no other one open issues.

**Comment by sevmardi** [comment]
I figured out the mistake from my side. Sorry about this.

**Comment by abhigoku10** [comment]
@sevmardi Hi i am also facing the same issue how did u solve it , can you share the solution

**Comment by sevmardi** [comment]
Hi @abhigoku10 I think I solved it by switching pytorch version and second, had small typo in the syntax. Share your code so I can have a look and compare with mine.

**Comment by TJUXJH** [comment]
hello @sevmardi  I also face the same problem when I train with GPU, could u please tell me the version of pytorch and the python u use to solve the problem?

**Comment by sevmardi** [comment]
hi @TJUXJH  I no longer remember. Try different versions. 0.4 I thought would work.
