### ISSUE TITLE
Training on Custom data and objects besides person 

### ISSUE THREAD

**Issue by abhigoku10** [yueruchen/Pedestrian-Synthesis-GAN#14]
HI @oyxhust @yueruchen  Thanks for wonderful code , when i train the model for custom object besides person it behaves differently , can you share some pointers what are the things i need to consider when i change the objects.
 Thanks in advance

**Comment by yifanjiang19** [comment]
Can you update the results you get?

**Comment by wuchenxi118** [comment]
I would like to ask why this problem occurs, thank you very much for your answer~

model [Pix2PixModel] was created
WARNING:root:Setting up a new session...
create web directory ./checkpoints/third_try/web...
Traceback (most recent call last):
  File "train.py", line 35, in <module>
    model.optimize_parameters(only_d)
  File "/home/wuchenxi/PS-gan-ori/models/pix2pix_model.py", line 179, in optimize_parameters
    self.backward_D_person()
  File "/home/wuchenxi/PS-gan-ori/models/pix2pix_model.py", line 131, in backward_D_person
    self.person_fake = self.netD_person.forward(self.person_crop_fake)
  File "/home/wuchenxi/PS-gan-ori/models/networks.py", line 470, in forward
    x = self.conv1(x)
  File "/home/wuchenxi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wuchenxi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: expected stride to be a single integer value or a list of 1 values to match the convolution dimensions, but got stride=[2, 2]

**Comment by wuchenxi118** [comment]
And  Is your code written in python2?

**Comment by HITxyer** [comment]
＠abhigoku10　I'd like to inquiry you how to change the data
