### ISSUE TITLE
 python test.py  --dataroot  ./datasets

### ISSUE THREAD

**Issue by TJUXJH** [yueruchen/Pedestrian-Synthesis-GAN#16]
hi, when I run    python test.py  --dataroot ./datasets 
some error occur,
CustomDatasetDataLoader
dataset [UnalignedDataset] was created
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    data_loader = CreateDataLoader(opt)
  File "/home/ben/workspace/PSGAN/data/data_loader.py", line 6, in CreateDataLoader
    data_loader.initialize(opt)
  File "/home/ben/workspace/PSGAN/data/custom_dataset_data_loader.py", line 30, in initialize
    self.dataset = CreateDataset(opt)
  File "/home/ben/workspace/PSGAN/data/custom_dataset_data_loader.py", line 20, in CreateDataset
    dataset.initialize(opt)
  File "/home/ben/workspace/PSGAN/data/unaligned_dataset.py", line 17, in initialize
    self.A_paths = make_dataset(self.dir_A)
TypeError: make_dataset() missing 1 required positional argument: 'dir_bbox'

**Comment by yifanjiang19** [comment]
Please refer to the https://github.com/yueruchen/Pedestrian-Synthesis-GAN/blob/ccb413df1e0dcdcb5333b9559e3681aac3c170d9/data/aligned_dataset.py#L19
