### ISSUE TITLE
TypeError: cuda() got an unexpected keyword argument 'device_id'

### ISSUE THREAD

**Issue by zxt-triumph** [yueruchen/Pedestrian-Synthesis-GAN#6]
I encountered a problem while training.
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    model = create_model(opt)
  File "/home/zxt/GAN Network/PS-GAN/models/models.py", line 19, in create_model
    model.initialize(opt)
  File "/home/zxt/GAN Network/PS-GAN/models/pix2pix_model.py", line 36, in initialize
    opt.which_model_netG, opt.norm, not opt.no_dropout, self.gpu_ids)
  File "/home/zxt/GAN Network/PS-GAN/models/networks.py", line 51, in define_G
    netG.cuda(device_id=gpu_ids[0])
TypeError: cuda() got an unexpected keyword argument 'device_id'
How to solve this problem？ Looking forward to your reply.

**Comment by yueruchen** [comment]
It’s due to the pytorch version. Just replace ‘device_id’ with ‘divice’.

**Comment by zxt-triumph** [comment]
Thank you for your reply! But I meet new problem.
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    model = create_model(opt)
  File "/home/image/zxt/PS-GAN/models/models.py", line 19, in create_model
    model.initialize(opt)
  File "/home/image/zxt/PS-GAN/models/pix2pix_model.py", line 43, in initialize
    self.netD_person = networks.define_person_D(opt.input_nc, opt.ndf, opt, use_sigmoid, self.gpu_ids)
  File "/home/image/zxt/PS-GAN/models/networks.py", line 85, in define_person_D
    netD = PersonDiscriminator(input_nc, ndf, use_sigmoid, gpu_ids=gpu_ids)
TypeError: __init__() got multiple values for keyword argument 'gpu_ids'

**Comment by yueruchen** [comment]
Could you please try to replace it with ```PersonDiscriminator(input_nc, ndf=ndf, use_sigmoid=use_sigmoid, gpu_ids=gpu_ids)``` ? It's about the problem of function arguments.

**Comment by yueruchen** [comment]
Could you please try to replace it with ```PersonDiscriminator(input_nc, ndf, gpu_ids=gpu_ids)``` ?

**Comment by zxt-triumph** [comment]
Thank you for your help!
