### ISSUE TITLE
The problem about training

### ISSUE THREAD

**Issue by nangongtianyi** [yueruchen/Pedestrian-Synthesis-GAN#7]
Hello, I meet the problem in the training process.How I could solve the problem?
Traceback (most recent call last):
File "train.py", line 13, in 
model = create_model(opt)
File "/home/image/fly/PS-GAN/models/models.py", line 19, in create_model
model.initialize(opt)
File "/home/image/fly/PS-GAN/models/pix2pix_model.py", line 43, in initialize
self.netD_person = networks.define_person_D(opt.input_nc, opt.ndf, opt, use_sigmoid, self.gpu_ids)
File "/home/image/fly/PS-GAN/models/networks.py", line 85, in define_person_D
netD = PersonDiscriminator(input_nc, ndf, use_sigmoid, gpu_ids=gpu_ids)
TypeError: init() got multiple values for keyword argument 'gpu_ids'

**Comment by yueruchen** [comment]
Could you please try to replace it with PersonDiscriminator(input_nc, ndf, gpu_ids=gpu_ids) ?
